### ISSUE TITLE
server always throws `PreconditionException("you are not alive to do any action.")` for caught thieves.

### ISSUE THREAD

**Issue by yjavaherian** [SharifAIChallenge/AIC22-Server#2]
based on game loop implementation in class `NextTurnWatcher`, a thief who is dead always tries to respond to the `GameTurnChangeEvent` of the turn on which the arrest is made, so this exception always occurs. hence not an "exception".

**Comment by pistolparody** [comment]
This is a client side issue and it was fixed  this morning.  (Except for cpp client)
please update your client version to the latest.
