### ISSUE TITLE
Clients don't have access to the initial balance of other type

### ISSUE THREAD

**Issue by yjavaherian** [SharifAIChallenge/AIC22-Server#7]
Current implementation of server has this inconsistency:
- thieves **don't know** the initial balance of police and vice versa
- thieves **know** the income of police and vice versa
Knowing one but not the other is useless; so server should either give clients the initial balance or remove income from `GameView`

**Comment by pistolparody** [comment]
According to this [link](https://t.me/AIC2022/1701), The support team guaranteed that the initial balance of both agent types are the same.
